/*2. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By
considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. Ans: 4613732*/
#include<stdio.h>
void main()
{
int fibo =0, a1=0, a2=1, sum = 0;
printf("The fibonacci sequence is: \n");
while(fibo<=4000000) {
fibo = a1+a2;
if(fibo%2==0){
sum=sum+ fibo;
}
a1=a2;
a2=fibo;
}
printf("\nThe sum of the series: %d", sum);
}
